import type { Persona, PersonalityStyle } from './types'

export const personalityStyles: PersonalityStyle[] = [
  {
    id: 'kind',
    label: '다정한',
    emoji: '💗',
    description: '내 마음을 잘 들어주고 따뜻하게 대답해요.',
  },
  {
    id: 'calm',
    label: '차분한',
    emoji: '🌙',
    description: '서두르지 않고 천천히 생각하며 말해요.',
  },
  {
    id: 'active',
    label: '활발한',
    emoji: '⚡',
    description: '반응이 크고 먼저 질문하며 대화를 이끌어요.',
  },
  {
    id: 'direct',
    label: '솔직한',
    emoji: '🎯',
    description: '생각을 돌려 말하지 않고 분명하게 표현해요.',
  },
]

export const personas: Persona[] = [
  {
    id: 'parent',
    label: '부모님',
    emoji: '👩',
    name: '지은',
    gender: '여성',
    relationship: '엄마',
    personality: '걱정이 많지만 내 이야기를 끝까지 들어줘요.',
    tone: '따뜻하고 차분해요',
    color: '#f8b7c7',
  },
  {
    id: 'teacher',
    label: '선생님',
    emoji: '👨‍🏫',
    name: '민준',
    gender: '남성',
    relationship: '담임 선생님',
    personality: '질문을 반기고, 순서대로 친절히 설명해 줘요.',
    tone: '또박또박 다정해요',
    color: '#9fc7f3',
  },
  {
    id: 'close-friend',
    label: '친한 친구',
    emoji: '🧒',
    name: '유나',
    gender: '여성',
    relationship: '같은 반 단짝',
    personality: '장난을 좋아하고 솔직한 이야기를 잘 들어줘요.',
    tone: '활발하고 편안해요',
    color: '#f5cf70',
  },
  {
    id: 'new-friend',
    label: '새 친구',
    emoji: '👦',
    name: '하람',
    gender: '남성',
    relationship: '처음 만난 반 친구',
    personality: '조금 수줍지만 먼저 웃어 주면 편하게 대답해요.',
    tone: '짧고 조심스러워요',
    color: '#9edfc4',
  },
  {
    id: 'sibling',
    label: '형제자매',
    emoji: '👧',
    name: '서아',
    gender: '여성',
    relationship: '두 살 위 누나',
    personality: '내 편이지만 가끔 물건을 허락 없이 빌려 가요.',
    tone: '장난스럽고 솔직해요',
    color: '#c6b2ed',
  },
]
